/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CollectionSelector: typeof import('./src/components/CollectionSelector.vue')['default']
    ColorLibrary: typeof import('./src/components/ColorLibrary.vue')['default']
    ColorPalette: typeof import('./src/components/ColorPalette.vue')['default']
    ColorPicker: typeof import('./src/components/ColorPicker.vue')['default']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    LoginModal: typeof import('./src/components/LoginModal.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PaletteList: typeof import('./src/components/PaletteList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SavePaletteModal: typeof import('./src/components/SavePaletteModal.vue')['default']
    SearchBox: typeof import('./src/components/SearchBox.vue')['default']
    SignUpModal: typeof import('./src/components/SignUpModal.vue')['default']
    UserProfileDropDown: typeof import('./src/components/UserProfileDropDown.vue')['default']
  }
}
